#!/usr/bin/env bash
#
# tests/lib/shims.sh -- PATH shims plus a throwaway copy of the repository, so
# the install scripts can be driven to their failure paths without root,
# without a kernel tree, without a network and without touching the real tree.
#
# Source it *after* tests/lib/assert.sh (it uses make_tmpdir):
#
#     . "$(dirname "$0")/lib/assert.sh"
#     . "$(dirname "$0")/lib/shims.sh"
#
#     shims=$(hda_shims_setup)      # a directory of fake commands
#     sandbox=$(hda_sandbox_setup)  # a copy of the files the installers need
#     ( cd "$sandbox" && PATH="$shims:$PATH" bash dkms.sh )
#
# Why shims
# ---------
# The installers are Linux-only: they write under /lib/modules, call dkms,
# depmod and make, and (on Ubuntu) extract the distribution kernel source.
# None of that can run on a developer machine or in CI, and none of it is what
# these tests are about -- they are about the *exit status* the installer
# reports.  Every command whose failure the installer is supposed to notice is
# therefore replaced by a shim that logs its argv and exits with a status the
# test chooses.
#
# The shim contract
# -----------------
#   HDA_SHIM_RC_<cmd>   per-command exit status, e.g. HDA_SHIM_RC_dkms=1
#   HDA_SHIM_RC         fallback for every shim (default 0)
#   HDA_SHIM_LOG        file the shims append their argv to, one line per call
#   HDA_SHIM_UNAME_R    what `uname -r` reports (default: the real release)
#   HDA_SHIM_FAKE_ROOT  `id` claims root unless this is 0
#
# Commands shimmed, and why each one is on the list:
#   dkms, depmod, make, tar, wget, curl, patch, dnf, sudo
#                       the commands the installers run that need root, a
#                       kernel tree or the network
#   ls                  the >= 6.17 installer ends its dkms branch with
#                       `ls -lA $update_dir` followed by a bare `exit`, so the
#                       status under test is ls's.  The shim makes ls succeed
#                       (that directory would exist on a real install) so the
#                       test measures the installer's own status handling
#                       rather than ls failing on a directory that is absent
#                       only because we are not root.
#   sed                 the pre-6.17 installer edits dkms.conf with GNU
#                       `sed -i`, which BSD sed rejects.  The shim keeps the
#                       script running on macOS; the edit itself cannot affect
#                       the exit status under test.  It also stops the real sed
#                       from leaving a dkms.conf.orig backup behind, which would
#                       flip the script onto its other sed branch on the next
#                       run in the same sandbox.
#   ln                  dkms.sh:37 symlinks the checkout into /usr/src, which is
#                       not writable here.  The shim keeps the sandbox
#                       independent of /usr/src's permissions.
#   uname, id           special-cased below.
#
# Compatible with bash 3.2 (macOS /bin/bash) and bash 5: no associative
# arrays, no `mapfile`, no `${var,,}`, no `local -n`.

# ---------------------------------------------------------------------------
# shim generation
# ---------------------------------------------------------------------------

# _hda_write_shim <dir> <cmd> -- write the generic shim for <cmd>.
#
# The shim is deliberately tiny and depends on nothing but bash builtins: it
# is invoked with the shim directory first on PATH, so it must not itself need
# a command that the shim directory shadows.
_hda_write_shim() {
  _dir=$1
  _cmd=$2
  cat > "$_dir/$_cmd" <<'HDA_SHIM'
#!/bin/bash
# HDA test shim -- generated by tests/lib/shims.sh, do not edit.
_cmd=${0##*/}
if [ -n "${HDA_SHIM_LOG:-}" ]; then
  {
    printf '%s' "$_cmd"
    for _a in "$@"; do printf ' %s' "$_a"; done
    printf '\n'
  } >> "$HDA_SHIM_LOG"
fi
_var="HDA_SHIM_RC_${_cmd//-/_}"
_rc=${!_var}
if [ -z "$_rc" ]; then _rc=${HDA_SHIM_RC:-0}; fi
exit "$_rc"
HDA_SHIM
  chmod +x "$_dir/$_cmd" || return 1
  return 0
}

# _hda_write_uname_shim <dir> -- `uname -r` reports $HDA_SHIM_UNAME_R when set,
# so the installer's kernel-version branches do not depend on the host kernel.
# Every other invocation is delegated to the real uname.
_hda_write_uname_shim() {
  _dir=$1
  _real=$(command -v uname) || return 1
  cat > "$_dir/uname" <<HDA_SHIM
#!/bin/bash
# HDA test shim for uname -- generated by tests/lib/shims.sh, do not edit.
if [ -n "\${HDA_SHIM_LOG:-}" ]; then printf 'uname %s\n' "\$*" >> "\$HDA_SHIM_LOG"; fi
if [ "\${1-}" = "-r" ] && [ -n "\${HDA_SHIM_UNAME_R-}" ]; then
  printf '%s\n' "\$HDA_SHIM_UNAME_R"
  exit 0
fi
exec "$_real" "\$@"
HDA_SHIM
  chmod +x "$_dir/uname" || return 1
  return 0
}

# _hda_write_id_shim <dir> -- `id` claims root, so a root check in an installer
# cannot stop the script before the failure path under test.  The scripts are
# documented as "should be run as root", so claiming root is the faithful
# simulation.  HDA_SHIM_FAKE_ROOT=0 delegates to the real id.
_hda_write_id_shim() {
  _dir=$1
  _real=$(command -v id) || return 1
  cat > "$_dir/id" <<HDA_SHIM
#!/bin/bash
# HDA test shim for id -- generated by tests/lib/shims.sh, do not edit.
if [ -n "\${HDA_SHIM_LOG:-}" ]; then printf 'id %s\n' "\$*" >> "\$HDA_SHIM_LOG"; fi
if [ "\${HDA_SHIM_FAKE_ROOT:-1}" = "1" ]; then
  case "\${1-}" in
    -u) printf '%s\n' "\${HDA_SHIM_ID_U:-0}"; exit 0 ;;
    -un|-nu) printf 'root\n'; exit 0 ;;
    -g) printf '0\n'; exit 0 ;;
    "") printf 'uid=%s(root) gid=0(root) groups=0(root)\n' "\${HDA_SHIM_ID_U:-0}"; exit 0 ;;
  esac
fi
exec "$_real" "\$@"
HDA_SHIM
  chmod +x "$_dir/id" || return 1
  return 0
}

# ---------------------------------------------------------------------------
# public interface
# ---------------------------------------------------------------------------

# hda_shims_setup -- create a shim directory, populate it and print its path.
# HDA_SHIM_LOG is exported and points at the argv log.  The directory is
# removed when the test process exits (it lives under make_tmpdir).
hda_shims_setup() {
  if ! command -v make_tmpdir > /dev/null 2>&1; then
    printf 'hda_shims_setup: source tests/lib/assert.sh first\n' >&2
    return 1
  fi
  _root=$(make_tmpdir) || return 1
  _dir="$_root/shims"
  mkdir -p "$_dir" || return 1
  HDA_SHIM_LOG="$_root/argv.log"
  : > "$HDA_SHIM_LOG" || return 1
  export HDA_SHIM_LOG
  for _c in wget curl tar make dkms depmod sudo ls sed patch dnf ln; do
    _hda_write_shim "$_dir" "$_c" || return 1
  done
  _hda_write_uname_shim "$_dir" || return 1
  _hda_write_id_shim "$_dir" || return 1
  HDA_SHIMS=$_dir
  export HDA_SHIMS
  printf '%s\n' "$_dir"
}

# hda_shim_clear -- forget every argv logged so far.
hda_shim_clear() {
  [ -n "${HDA_SHIM_LOG:-}" ] || return 0
  : > "$HDA_SHIM_LOG"
}

# hda_shim_calls <cmd> -- print the argv lines logged for <cmd>, one per call.
hda_shim_calls() {
  [ -n "${HDA_SHIM_LOG:-}" ] || return 0
  [ -f "$HDA_SHIM_LOG" ] || return 0
  grep "^$1 " "$HDA_SHIM_LOG" 2>/dev/null
  return 0
}

# hda_shim_rc <cmd> <status> -- make the shim for <cmd> exit with <status>.
hda_shim_rc() {
  export "HDA_SHIM_RC_$1=$2"
}

# hda_shim_rc_clear <cmd>... -- drop the per-command overrides, so the shims
# fall back to HDA_SHIM_RC (default 0, i.e. success).
hda_shim_rc_clear() {
  for _c in "$@"; do
    unset "HDA_SHIM_RC_$_c"
  done
}

# hda_sandbox_setup -- print the path of a throwaway copy of the repository.
# The installers mutate dkms.conf, create build/ and write under /lib/modules,
# so they must never run in the real tree.  The copy is the checkout minus
# .git (a file in a worktree, and useless here), tests/ (31 MB of WAV fixtures)
# and build/ (a previous run's leftovers); that is ~1 MB and keeps the sandbox
# faithful for every code path, including the ones this machine cannot reach
# today.  Dotfiles are skipped too: no installer reads one.
hda_sandbox_setup() {
  if ! command -v make_tmpdir > /dev/null 2>&1; then
    printf 'hda_sandbox_setup: source tests/lib/assert.sh first\n' >&2
    return 1
  fi
  _repo=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd) || return 1
  _dir=$(make_tmpdir) || return 1
  for _f in dkms.sh dkms.conf install.cirrus.driver.sh install.cirrus.driver.pre617.sh; do
    if [ ! -f "$_repo/$_f" ]; then
      printf 'hda_sandbox_setup: missing %s\n' "$_repo/$_f" >&2
      return 1
    fi
  done
  for _e in "$_repo"/*; do
    [ -e "$_e" ] || continue
    case "${_e##*/}" in
      tests|build) continue ;;
    esac
    cp -R "$_e" "$_dir/" || return 1
  done
  HDA_SANDBOX=$_dir
  export HDA_SANDBOX
  printf '%s\n' "$_dir"
}

# ---------------------------------------------------------------------------
# driving the installers
# ---------------------------------------------------------------------------

# hda_installer_run <script> [args...] -- run <script> inside $HDA_SANDBOX with
# the shims first on PATH.  Sets HDA_INSTALLER_RC to the exit status and
# HDA_INSTALLER_OUTPUT to its combined output.  Never fails the test itself:
# the caller decides what the status means.
hda_installer_run() {
  if [ -z "${HDA_SANDBOX:-}" ] || [ -z "${HDA_SHIMS:-}" ]; then
    printf 'hda_installer_run: call hda_shims_setup and hda_sandbox_setup first\n' >&2
    return 1
  fi
  _script=$1
  shift
  HDA_INSTALLER_OUTPUT=$( cd "$HDA_SANDBOX" && PATH="$HDA_SHIMS:$PATH" bash "$_script" "$@" 2>&1 )
  HDA_INSTALLER_RC=$?
  return 0
}

# hda_installer_output_oneline -- the last run's output, newlines folded, for
# embedding in a failure message.
hda_installer_output_oneline() {
  printf '%s' "${HDA_INSTALLER_OUTPUT:-}" | tr '\n' '|'
}

# hda_assert_installer_nonzero <script> <scenario> [args...] -- the installer
# must exit non-zero when the command named by <scenario> fails.  The failure
# message names the script and the scenario, which is the whole point of this
# suite: a bare `exit` after a failed command reports success to the caller.
hda_assert_installer_nonzero() {
  _script=$1
  _scenario=$2
  shift 2
  hda_installer_run "$_script" "$@" || return 1
  if [ "$HDA_INSTALLER_RC" -ne 0 ]; then
    printf 'PASS: %s [%s] exited %s\n' "$_script" "$_scenario" "$HDA_INSTALLER_RC"
    return 0
  fi
  _hda_fail "$_script: $_scenario exited 0, expected non-zero -- the installer reported success after the failure (output: $(hda_installer_output_oneline))"
  return 1
}

# hda_assert_installer_zero <script> <scenario> [args...] -- the positive
# control: with every shim succeeding the installer must exit 0.
hda_assert_installer_zero() {
  _script=$1
  _scenario=$2
  shift 2
  hda_installer_run "$_script" "$@" || return 1
  if [ "$HDA_INSTALLER_RC" -eq 0 ]; then
    printf 'PASS: %s [%s] exited 0\n' "$_script" "$_scenario"
    return 0
  fi
  _hda_fail "$_script: $_scenario exited $HDA_INSTALLER_RC, expected 0 -- the installer failed although every command it ran succeeded (output: $(hda_installer_output_oneline))"
  return 1
}

# hda_assert_shim_called <cmd> <needle> <msg> -- the shim log shows <cmd> was
# invoked with an argument containing <needle>.  Used to prove a test is not
# vacuous: the installer really did reach the command whose failure it is
# supposed to report.
hda_assert_shim_called() {
  _calls=$(hda_shim_calls "$1")
  case "$_calls" in
    *"$2"*) return 0 ;;
  esac
  _hda_fail "$3 (no '$1' call containing '$2' in the shim log; saw: $(printf '%s' "$_calls" | tr '\n' '|'))"
  return 1
}

# ---------------------------------------------------------------------------
# cases this machine cannot drive
# ---------------------------------------------------------------------------

# hda_non_dkms_blocker <uname> -- print why the installer's non-dkms code path
# cannot be driven on this machine, or nothing at all when it can.
#
# The non-dkms path is where `make install` and the `wget`/`tar` kernel-source
# download run.  Two of its preconditions are outside PATH-shim reach:
#
#   1. the kernel-headers probe, `[ -d /usr/src/linux-headers-<uname> ]` and
#      three siblings (install.cirrus.driver.sh:97-128, pre617:114-145).  It is
#      a bash builtin on an absolute path, so no shim can influence it, and
#      /usr/src is not writable on macOS.  When it fails the installer exits 1
#      at line 126 / 143, long before the code under test.
#   2. `mkdir $update_dir` under /lib/modules (install.cirrus.driver.sh:303),
#      which needs root.  Without it the installer dies at the `mv` of the
#      kernel tree's Makefiles, again before `make install`.
#
# A test that ignored either precondition would still see a non-zero exit and
# "pass" for the wrong reason, so the cases are reported as BLOCKED instead.
hda_non_dkms_blocker() {
  _u=$1
  _found=
  for _d in "/usr/src/linux-headers-$_u" "/usr/src/kernels/$_u" "/usr/lib/modules/$_u" "/usr/src/kernel-headers-$_u"; do
    if [ -d "$_d" ]; then _found=$_d; break; fi
  done
  if [ -z "$_found" ]; then
    printf 'no kernel headers for %s: none of /usr/src/linux-headers-%s, /usr/src/kernels/%s, /usr/lib/modules/%s, /usr/src/kernel-headers-%s exists, and /usr/src is not writable, so the installer exits 1 at its headers probe (install.cirrus.driver.sh:126, pre617:143) before the code under test' \
      "$_u" "$_u" "$_u" "$_u" "$_u"
    return 0
  fi
  _moddir=/lib/modules
  [ -d /usr/lib/modules ] && _moddir=/usr/lib/modules
  if ! mkdir -p "$_moddir/$_u/updates" 2>/dev/null; then
    printf '%s exists but %s/%s/updates cannot be created (needs root), so the installer exits at its `mkdir $update_dir` (install.cirrus.driver.sh:303) before the code under test' \
      "$_found" "$_moddir" "$_u"
    return 0
  fi
  rmdir "$_moddir/$_u/updates" 2>/dev/null
  rmdir "$_moddir/$_u" 2>/dev/null
  return 0
}

# hda_blocked <case> <reason> -- record a case that cannot be driven on this
# machine.  Prints a BLOCKED line and does not fail the test file: the blocker
# is an environment limitation, not a defect in the code under test.  The
# reason is repeated in the PR description.
hda_blocked() {
  HDA_BLOCKED_COUNT=$(( ${HDA_BLOCKED_COUNT:-0} + 1 ))
  printf 'BLOCKED: %s -- %s\n' "$1" "$2" >&2
  return 0
}

# hda_blocked_summary -- one line naming how many cases were blocked, so a run
# that silently covered less than it looks like cannot go unnoticed.
hda_blocked_summary() {
  if [ "${HDA_BLOCKED_COUNT:-0}" -gt 0 ]; then
    printf 'BLOCKED: %s case(s) could not be driven on this machine (see the BLOCKED lines above)\n' "$HDA_BLOCKED_COUNT" >&2
  fi
  return 0
}
